import {chromium} from 'playwright';import assert from 'node:assert/strict';import {readFile,writeFile} from 'node:fs/promises';
const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1536,height:1080}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const style=(selector,property)=>page.locator(selector).first().evaluate((e,p)=>getComputedStyle(e)[p],property);
const settle=async()=>{await page.mouse.move(0,0);await page.waitForTimeout(250);};
try{
await page.goto(process.env.CLOUDCOMMON_DEMO_URL ?? 'http://127.0.0.1:5188',{waitUntil:'networkidle'});
await page.getByLabel('Preset',{exact:true}).selectOption('Violet');await settle();
assert.equal(await page.locator('.live-login .input-content input').count(),1);
await page.locator('.live-login input').fill('designer@example.com');
await page.locator('.live-commerce .commerce-input-group input').fill('CLOUD20');await page.locator('.live-commerce .commerce-input-group input').blur();await settle();
const primary=await style('.preview-actions button','backgroundColor');
assert.equal(await style('.live-cdm button:not(._selected):not(:disabled)','backgroundColor'),'rgba(0, 0, 0, 0)','CDM unselected options stay transparent');
assert.equal(await style('.live-cdm button._selected','backgroundColor'),primary,'CDM selection follows shared primary');
assert.equal(await style('.live-commerce button','backgroundColor'),await style('.live-login input','backgroundColor'),'Commerce secondary action retains its surface background');

await page.locator('.live-commerce button').click();await page.getByRole('status').filter({hasText:'Promotion CLOUD20 applied in this demo.'}).waitFor();await settle();
await page.getByLabel('Commerce-only override',{exact:true}).check();await settle();
assert.equal(await style('.live-commerce button','backgroundColor'),'rgb(0, 105, 92)');
assert.equal(await style('.live-cdm button._selected','backgroundColor'),primary,'Override stays with Commerce');
await page.getByLabel('Commerce-only override',{exact:true}).uncheck();
await page.getByLabel('Appearance',{exact:true}).selectOption('Dark');await settle();
assert.notEqual(await style('.live-login .input-content input','backgroundColor'),'rgb(255, 255, 255)');
assert.equal(await style('.live-login .input-content input','backgroundColor'),await style('.live-commerce .commerce-input-group input','backgroundColor'));
assert.equal(await style('.cloudgrid','color'),await style('.live-login .input-content input','color'));
await page.getByLabel('Typography',{exact:true}).selectOption('Georgia, serif');await settle();
assert.equal(await style('.live-login input','fontFamily'),'Georgia, serif');
assert.equal(await style('.live-cdm button','fontFamily'),'Georgia, serif');
await page.getByLabel('Button CSS override').fill('background: linear-gradient(90deg, #6750a4, #007e87); border-radius: 20px;');
await page.getByRole('button',{name:'Apply override',exact:true}).click();await settle();
assert.match(await style('.preview-actions button','backgroundImage'),/linear-gradient/);
assert.equal(await style('.live-cdm button:not(._selected):not(:disabled)','backgroundColor'),'rgba(0, 0, 0, 0)','Generic button overrides do not fill selection controls');
assert.equal(await style('.live-cdm button:not(._selected):not(:disabled)','borderRadius'),'3px');
await page.locator('.live-login input').focus();await page.waitForTimeout(250);
assert.equal(await style('.live-login input','outlineStyle'),'solid');
assert.equal(await style('.live-cdm button:disabled','opacity'),'0.5');
await page.screenshot({path:'artifacts/library-integration-dark.png',fullPage:true});
const external=await browser.newPage();
const css=await readFile('CloudCommon.Theming.Blazor/wwwroot/css/theme.css','utf8');
await external.setContent('<style>'+css+'</style><button data-cloud-element="button">Document action</button>');
const light=await external.locator('button').evaluate(e=>getComputedStyle(e).backgroundColor);
await external.evaluate(()=>document.documentElement.dataset.amcTheme='dark');await external.waitForTimeout(250);
assert.notEqual(await external.locator('button').evaluate(e=>getComputedStyle(e).backgroundColor),light);
await external.evaluate(()=>document.documentElement.dataset.amcTheme='system');await external.emulateMedia({colorScheme:'light'});await external.waitForTimeout(250);
assert.equal(await external.locator('button').evaluate(e=>getComputedStyle(e).backgroundColor),light);
await external.emulateMedia({colorScheme:'dark'});await external.waitForTimeout(250);
assert.notEqual(await external.locator('button').evaluate(e=>getComputedStyle(e).backgroundColor),light);
await external.close();assert.deepEqual(errors,[]);
await writeFile('artifacts/library-integration-results.json',JSON.stringify({passed:true,checks:['real Login input','real Commerce coupon interaction','real CDM selections','shared palette','Commerce-only override','dark input surfaces','grid text inheritance','typography','generic element overrides preserve CDM selection design','keyboard focus','disabled state','document light/dark/system']},null,2));
console.log('Passed 12 cross-library browser checks.');
}finally{await browser.close();}
