import { chromium } from 'playwright';
import { mkdir, writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const browser = await chromium.launch({ channel: 'msedge', headless: true });
const page = await browser.newPage({ viewport: { width: 1536, height: 1080 } });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
await mkdir('artifacts', { recursive: true });
try {
  await page.goto(process.env.CLOUDCOMMON_DEMO_URL ?? 'http://127.0.0.1:5188', { waitUntil: 'networkidle' });
  await page.getByRole('button', { name: 'Try primary action', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Primary action activated.' }).waitFor();
  assert.equal(await page.locator('.cloudgrid').count(), 1, 'Actual CloudDataGrid must render');
  const primary = page.getByRole('button', { name: 'Try primary action', exact: true });
  const color = () => primary.evaluate(element => getComputedStyle(element).backgroundColor);
  await page.mouse.move(0, 0);
  await page.waitForTimeout(200);
  const gray = await color();
  await page.getByLabel('Preset', { exact: true }).selectOption('Violet');
  await page.waitForTimeout(300);
  assert.notEqual(await color(), gray);
  await page.getByLabel('Appearance', { exact: true }).selectOption('Dark');
  await page.waitForTimeout(300);
  assert.equal(await page.locator('.preview-scope').getAttribute('data-amc-theme'), 'dark');
  await page.getByLabel('Appearance', { exact: true }).selectOption('Light');
  await page.getByLabel('Button CSS override').fill('background: linear-gradient(90deg, #6750a4, #007e87); border-radius: 20px;');
  await page.getByRole('button', { name: 'Apply override', exact: true }).click();
  await page.waitForTimeout(300);
  assert.match(await primary.evaluate(element => getComputedStyle(element).backgroundImage), /linear-gradient/);
  assert.equal(await primary.evaluate(element => getComputedStyle(element).borderRadius), '20px');
  await page.getByLabel('Button CSS override').fill('position: fixed');
  await page.getByRole('button', { name: 'Apply override', exact: true }).click();
  await page.getByRole('alert').filter({ hasText: 'not a supported visual override' }).waitFor();
  await page.getByRole('button', { name: 'Reset to grayscale', exact: true }).click();
  await page.getByLabel('Preset', { exact: true }).selectOption('Violet');
  await page.waitForTimeout(300);
  await page.screenshot({ path: 'artifacts/workshop-desktop.png', fullPage: true });
  await page.getByRole('tab', { name: 'Code', exact: true }).click();
  await page.getByText('Use this configuration', { exact: true }).waitFor();
  const href = await page.getByRole('link', { name: 'Download theme.css', exact: true }).getAttribute('href');
  const css = Buffer.from(href.split(',')[1], 'base64').toString();
  assert.match(css, /--amc-primary-500:#6750a4/);
  const external = await browser.newPage();
  await external.setContent('<style>' + css + '</style><div class="cloud-theme"><button data-cloud-element="button">External</button></div>');
  const externalButton = external.getByRole('button', { name: 'External' });
  assert.equal(await externalButton.evaluate(element => getComputedStyle(element).backgroundColor), 'rgb(103, 80, 164)');
  await external.addStyleTag({ content: '.cloud-theme { --amc-color-primary: #123456; }' });
  await external.waitForTimeout(250);
  assert.equal(await externalButton.evaluate(element => getComputedStyle(element).backgroundColor), 'rgb(18, 52, 86)');
  await external.addStyleTag({ content: '[data-cloud-element="button"] { border-radius: 30px; }' });
  assert.equal(await externalButton.evaluate(element => getComputedStyle(element).borderRadius), '30px');
  await external.close();
  await page.getByRole('button', { name: 'Scope isolation', exact: true }).click();
  const inner = page.getByRole('button', { name: 'Independent action', exact: true });
  const innerColor = await inner.evaluate(element => getComputedStyle(element).backgroundColor);
  await page.getByLabel('Preset', { exact: true }).selectOption('Amber');
  await page.waitForTimeout(300);
  assert.equal(await inner.evaluate(element => getComputedStyle(element).backgroundColor), innerColor);
  await page.getByRole('button', { name: 'Palette & tokens', exact: true }).click();
  await page.locator('.palette-swatch').first().waitFor();
  assert.equal(await page.locator('.palette-swatch').count(), 66);
  await page.getByRole('button', { name: 'Shared models', exact: true }).click();
  await page.getByLabel('Amount', { exact: true }).fill('12.34');
  await page.getByLabel('Amount', { exact: true }).blur();
  await page.waitForTimeout(150);
  assert.match(await page.locator('output').textContent(), /12.34/);
  await page.getByRole('tab', { name: 'Instructions', exact: true }).click();
  await page.getByRole('heading', { name: 'Integrate the shared foundation', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Theme playground', exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'artifacts/workshop-mobile.png', fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'No mobile horizontal overflow');
  assert.deepEqual(errors, []);
  await writeFile('artifacts/browser-results.json', JSON.stringify({ passed: true, checks: ['real grid', 'presets', 'dark mode', 'partial overrides', 'gradients', 'CSS rejection', 'portable CSS', 'external overrides', 'scope isolation', 'palette', 'models', 'instructions', 'mobile'] }, null, 2));
  console.log('Passed 13 browser checks; desktop and mobile screenshots saved.');
} finally {
  await browser.close();
}
