<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <Version>0.1.0</Version>
    <Authors>Angry Monkey</Authors>
    <Company>Angry Monkey</Company>
    <PackageProjectUrl>https://angrymonkeycloud.com</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup Condition="'$(IsPackable)' != 'false'">
    <None Include="$(MSBuildProjectDirectory)/README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>

